added recorder
NichWayoe/FindMe pull request #28
Opened 2020-09-19 22:58 UTC by NichWayoe

-[x] created a recorder class 
-[x] method to start recording
-[x[ method to stop recording

2020-09-26 23:11 UTC, joesus requested changes
Looks good for objective-c. Next pr in Swift please. :)

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.h
> +- (void)startRecording:(void(^)(NSError * error, BOOL isStarted))completion;
don't need recording since you're already in the recorder.
```suggestion
- (void)start:(void(^)(NSError * error, BOOL isStarted))completion;
```

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.h
> +@interface RecordingManager : NSObject
```suggestion
@interface Recorder : NSObject
```

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.m
> +        NSURL *baseUrl = [NSURL fileURLWithPath:@"file:/Users/nwayoe/Documents/"];
Find better way to do this probably.

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.m
> +        if (self.recorder) {
Meant to keep this?

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.m
> +   }
```suggestion
if (!self.recorder.isRecording) {
    completion(nil, [self.recorder record]);
}
```

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.m
> +      }
Needs indentation fixes. cmd-a ctrl-i

2020-09-26 23:11 UTC, joesus commented on FindMe/Recording/RecordingManager.m
> +
newline

2020-09-27 03:34 UTC, NichWayoe commented on FindMe/Recording/RecordingManager.m
> +        if (self.recorder) {
No, I was using just for testing.

2020-10-03 19:14 UTC, merged